<template>
    <div id='app'>
        <br><br><br><br>
        <div class="f">
            <el-row>
                <el-col :xs="24" :sm="24" :md="24" :lg="24" :xl="24" v-for="(item,index) in company_applying" :key="item" :offset="0">
                     <el-card  shadow="hover" style="border-radius:25px">
                         <el-row>
                             <el-col :span="12">
                                <img src="../../assets/logo.png" class="image">
                             </el-col>
                             <el-col :span="12">
                                <div style="padding: 14px;">
                                    <span>公司编号：{{item.company_id}}</span><br>
                                    <span>公司名：{{item.company_name}}</span><br><br>
                                    <el-button @click="turnToCompanyApplyingDetail(index)" size="mini">详情</el-button>
                                </div>
                             </el-col>
                         </el-row>                     
                     </el-card>
                </el-col>
            </el-row>
        </div>
    </div>
</template>
<script>
export default {
    name:'companyapplying',
    data(){
        return{
            company_applying:[
                {
                    company_id:1,
                    company_name:'公司1',
                    company_account:'company1',
                    company_password:'123',
                    province:'Zhejiang',
                    city:'Hangzhou',
                    company_address:'中国计量大学',
                    company_tel:'85192626',
                    company_email:'@qq.com',
                    company_aliPay:'aliPay32543261423',
                    company_taxNum:'taxNum34675247489093',


                },
                 {
                    company_id:2,
                    company_name:'公司2',
                    company_account:'company2',
                    company_password:'1233',
                    province:'Zhejiang',
                    city:'Hangzhou',
                    company_address:'中国计量大学',
                    company_tel:'85192626',
                    company_email:'@qq.com',
                    company_aliPay:'aliPay32543261423',
                    company_taxNum:'taxNum34675247489093',
                },
                 {
                    company_id:3,
                    company_name:'公司3',
                    company_account:'company3',
                    company_password:'1234',
                    province:'Zhejiang',
                    city:'Hangzhou',
                    company_address:'中国计量大学',
                    company_tel:'85192626',
                    company_email:'@qq.com',
                    company_aliPay:'aliPay32543261423',
                    company_taxNum:'taxNum34675247489093',
                },
                 {
                    company_id:4,
                    company_name:'公司4',
                    company_account:'company4',
                    company_password:'123',
                    province:'Zhejiang',
                    city:'Hangzhou',
                    company_address:'中国计量大学',
                    company_tel:'85192626',
                    company_email:'@qq.com',
                    company_aliPay:'aliPay32543261423',
                    company_taxNum:'taxNum34675247489093',
                },

                 {
                    company_id:5,
                    company_name:'公司5',
                    company_account:'company5',
                    company_password:'123',
                    province:'Zhejiang',
                    city:'Hangzhou',
                    company_address:'中国计量大学',
                    company_tel:'85192626',
                    company_email:'@qq.com',
                    company_aliPay:'aliPay32543261423',
                    company_taxNum:'taxNum34675247489093',
                },
                 {
                    company_id:6,
                    company_name:'公司6',
                    company_account:'company6',
                    company_password:'123',
                    province:'Zhejiang',
                    city:'Hangzhou',
                    company_address:'中国计量大学',
                    company_tel:'85192626',
                    company_email:'@qq.com',
                    company_aliPay:'aliPay32543261423',
                    company_taxNum:'taxNum34675247489093',
                },
                 {
                    company_id:7,
                    company_name:'公司7',
                    company_account:'company7',
                    company_password:'123',
                    province:'Zhejiang',
                    city:'Hangzhou',
                    company_address:'中国计量大学',
                    company_tel:'85192626',
                    company_email:'@qq.com',
                    company_aliPay:'aliPay32543261423',
                    company_taxNum:'taxNum34675247489093',
                },
                 {
                    company_id:8,
                    company_name:'公司8',
                    company_account:'company8',
                    company_password:'123',
                    province:'Zhejiang',
                    city:'Hangzhou',
                    company_address:'中国计量大学',
                    company_tel:'85192626',
                    company_email:'@qq.com',
                    company_aliPay:'aliPay32543261423',
                    company_taxNum:'taxNum34675247489093',
                },
                 {
                    company_id:9,
                    company_name:'公司9',
                    company_account:'company9',
                    company_password:'123',
                    province:'Zhejiang',
                    city:'Hangzhou',
                    company_address:'中国计量大学',
                    company_tel:'85192626',
                    company_email:'@qq.com',
                    company_aliPay:'aliPay32543261423',
                    company_taxNum:'taxNum34675247489093',
                },
                 {
                    company_id:10,
                    company_name:'公司10',
                    company_account:'company10',
                    company_password:'123',
                    province:'Zhejiang',
                    city:'Hangzhou',
                    company_address:'中国计量大学',
                    company_tel:'85192626',
                    company_email:'@qq.com',
                    company_aliPay:'aliPay32543261423',
                    company_taxNum:'taxNum34675247489093',
                },
            ]
        }
    },
    methods:{
        turnToCompanyApplyingDetail:function(index){
            this.$router.push({
                path:'/managerafterlogin/companyapplydetail',
                query:{
                     
                     company_id:this.company_applying[index].company_id,
                     company_name:this.company_applying[index].company_name,
                     company_account:this.company_applying[index].company_account,
                     company_password:this.company_applying[index].company_password,
                     provice:this.company_applying[index].province,
                     city:this.company_applying[index].city,
                     company_address:this.company_applying[index].company_address,
                     company_tel:this.company_applying[index].company_tel,
                     company_email:this.company_applying[index].company_email,
                     company_aliPay:this.company_applying[index].company_aliPay,
                     company_taxNum:this.company_applying[index].company_taxNum,
                     manager_id:this.$route.query.manager_id
                }
            });
            this.$router.go(0);
        },

    }
}
</script>
<style>
.f{
   
    font-size:1.5rem;
    margin-left:5rem;
    margin-right:5rem;
    margin-top:2rem;
    text-align: center;
    background-color: white;
}
@media (max-width: 960px) {
    .f{
        font-size:10px;
        margin:0.3em;
        text-align: left;
    }
    .el-button{
        font-size:10px;
    }
    .image{
        width:80%;
    }    
}
</style>
